# Pandas

# #Pandas is an open‑source Python library that provides fast, flexible data structures—mainly Series and DataFrame—for data manipulation and analysis, built on top of NumPy.

In [1]:
# developed by mckinney in 20098

In [2]:
import random

In [3]:
import pandas as pd

In [4]:
pd.read_csv("scopus_export_Sep 10-2026_aabe70d9-6d7a-4118-8507-c440c931a943 (1).csv")

FileNotFoundError: [Errno 2] No such file or directory: 'scopus_export_Sep 10-2026_aabe70d9-6d7a-4118-8507-c440c931a943 (1).csv'

In [ ]:
import os

print(os.getcwd())

In [ ]:
import os

print(os.listdir())

In [ ]:
import os

print(os.getcwd())

In [ ]:
import os

print("Current Working Directory:")
print(os.getcwd())

print("\nFiles in Current Folder:")
print(os.listdir())

In [ ]:
import os

folder = r"C:\Users\Naquiuzzaman\Desktop\DATA SCIENCE\Pandas Advance ,Plotly Basics"

print("Folder exists:", os.path.exists(folder))

if os.path.exists(folder):
    for file in os.listdir(folder):
        if file.lower().endswith(".csv"):
            print(file)

In [ ]:
import pandas as pd

df = pd.read_csv("scopus_export_Sep 10-2026_aabe70d9-6d7a-4118-8507-c440c931a943 (1).csv")

df.head()

In [ ]:
df = pd.read_csv("D:\submission.csv")

In [ ]:
df.head()

In [ ]:
df = pd.read_csv("scopus_export_Sep 10-2026_aabe70d9-6d7a-4118-8507-c440c931a943 (1).csv",header = None)

df.head()

In [ ]:
df = pd.read_csv("scopus_export_Sep 10-2026_aabe70d9-6d7a-4118-8507-c440c931a943 (1).csv",skiprows=3)

df.head()

In [ ]:
df = pd.read_csv("scopus_export_Sep 10-2026_aabe70d9-6d7a-4118-8507-c440c931a943 (1).csv",usecols = ["Authors", "Author full names"])

df.head()

In [ ]:
df = pd.read_csv("scopus_export_Sep 10-2026_aabe70d9-6d7a-4118-8507-c440c931a943 (1).csv")

df.head()

In [ ]:
# datafrane >> table

In [ ]:
# Dta structure 
# one column >> this is series
# 2 dimensional in nature (rows and columns ) >> dataframe

In [ ]:
df

In [ ]:
type(df)

In [ ]:
df ["PubMed ID"]

In [ ]:
type(df ["PubMed ID"])

In [ ]:
#multiple series makes a draftframe

In [ ]:
l = [1,2,3,4,5]
s = pd.Series(l)

In [ ]:
type (s)

In [ ]:
s

In [ ]:
d = pd.Series([100,300,500,700,900], index = ["Md Naquiuzzaman", "Marhaba", "Marushat","Queen","King"])

In [ ]:
d

In [ ]:
d ["King"]

In [ ]:
d.reset_index(drop = True , inplace = True) #drop = True  >> drop the original index
#inplace True >> modify original Series

In [ ]:
d

In [ ]:
df.shape # This will give you rows and column

In [ ]:
df.columns

# Advance

In [ ]:
df.info()

In [ ]:
df.dtypes

In [ ]:
df["Authors"]

In [ ]:
df[["Authors","Author full names"]]

In [ ]:
list(df["Author full names"])

In [ ]:
print(list)

In [ ]:
list(df["Author full names"])

In [ ]:
 df

In [ ]:
df["new_column"] = "Md Naquiuzzaman"
df

In [ ]:
df["new_column"] = list(range(len(df)))

In [ ]:
df

In [ ]:
list(range(len(df)))

In [ ]:
df.columns

In [ ]:
df[['Authors', 'Author(s) ID' , 'Author full names']]

In [ ]:
import pandas as pd

# Read the CSV file
df = pd.read_csv(r"D:\churnguard_targeted_retention_list.csv")

# Convert CSV to Excel
df.to_excel(r"D:\churnguard_targeted_retention_list.xlsx", index=False)

print("File converted successfully!")

In [ ]:
import pandas as pd

df1 = pd.read_excel(r"D:\churnguard_targeted_retention_list.xlsx")

df1

In [ ]:
df1.shape

In [ ]:
df1.columns

In [ ]:
df1.dtypes

In [ ]:
df1.info()

In [ ]:
df1.head()

In [ ]:
df1.tail()

In [ ]:
df1.head(2)

In [ ]:
df1.info()

In [ ]:
df1.sample(4)

In [ ]:
df1[["partner"]]

In [ ]:
bf = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
bf

In [ ]:
bf.describe()  # df.describe() gives statistical information about numerical column

In [ ]:
bf.dtypes

In [ ]:
bf.dtypes == "object"

In [ ]:
bf.dtypes[bf.dtypes == "object"]

In [ ]:
bf.dtypes[bf.dtypes == "object"].index

In [ ]:
bf[bf.dtypes[bf.dtypes == "object"].index]

In [ ]:
bf[bf.dtypes[bf.dtypes != "object"].index]

In [ ]:
bf[bf.dtypes[bf.dtypes == "object"].index].describe()

In [ ]:
s = bf[bf.dtypes[bf.dtypes != "object"].index].describe().reset_index()

In [ ]:
s

In [ ]:
round (s["Pclass"],1)

In [ ]:
bf.describe(include = "object")

In [ ]:
bf.describe(include = "all")

In [ ]:
#iloc >> integeger/implict
#loc >> explicit index

In [ ]:
s.iloc[0:100]

In [ ]:
bf.iloc[0:5]

In [ ]:
df.loc[0:5]

In [ ]:
df.loc[5:6
    ]

In [ ]:
df.iloc[5:6
    ]

In [ ]:
df.iloc[3:5, 7:9]

In [ ]:
bf

In [ ]:
bf["Pclass"].nunique()

In [ ]:
bf["Name"].nunique()

In [ ]:
bf["Sex"].nunique()

In [ ]:
bf["Sex"].value_counts # you can visualize the male kon hai or female kon hai through the value_counts

In [ ]:
bf["Sex"].value_counts(normalize = True) # Through normalise you can see the sam,e data ij percentage

In [ ]:
bf["Sex"].nunique()

In [ ]:
bf

In [ ]:
bf.drop(1, inplace = True)

In [ ]:
bf

In [ ]:
# for dropping the passenger class 
bf.drop("Pclass",axis =1,inplace = True)

In [ ]:
bf

In [ ]:
bf.sort_values( by = "Name")

In [ ]:
bf.sort_values( by = "Age")

# PANDAS 2

In [3]:
import pandas as pd
df = pd.read_csv ("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [7]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [8]:
df.sample()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5,NaN,S

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 118.9 KB

In [10]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 118.9 KB

In [12]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [13]:
df[0:100:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,NaN,C
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0000,NaN,S
40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.0,1,0,7546,9.4750,NaN,S
45,46,0,3,"Rogers, Mr. William John",male,NaN,0,0,S.C./A.4. 23567,8.0500,NaN,S
50,51,0,3,"Panula, Master. Juha Niilo",male,7.0,4,1,3101295,39.6875,NaN,S
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
60,61,0,3,"Sirayanian, Mr. Orsen",male,22.0,0,0,2669,7.2292,NaN,C
65,66,1,3,"Moubarek, Master. Gerios",male,NaN,1,1,2661,15.2458,NaN,C
70,71,0,2,"Jenkin, Mr. Stephen Curnow",male,32.0,0,0,C.A. 33111,10.5000,NaN,S
75,76,0,3,"Moen, Mr. Sigurd Hansen",male,25.0,0,0,348123,7.6500,F G73,S
80,81,0,3,"Waelens, Mr. Achille",male,22.0,0,0,345767,9.0000,NaN,S
85,86,1,3,"Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...",female,33.0,3,0,3101278,15.8500,NaN,S
90,91,0,3,"Christmann, Mr. Emil",male,29.0,0,0,343276,8.0500,NaN,S
95,96,0,3,"Shorney, Mr. Charles Joseph",male,NaN,0,0,374910,8.0500,NaN,S

In [ ]:
#df.ilock #by deafault integer acesses 
#df.ilock # named indexes

In [14]:
df["Sex"] . unique()

<ArrowStringArray>
['male', 'female']
Length: 2, dtype: str

In [15]:
df["Sex"] . nunique()

2

In [16]:
df ["Embarked"] .value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [18]:
df.isna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [19]:
df.isna().sum ()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64